# Generated by Django 2.1 on 2018-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('Легко', 'Легко'), ('Легко', 'Средняя'), ('Легко', 'Тяжёлая')], default='Easy', max_length=8),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
