# Generated by Django 2.1 on 2018-08-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180810_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.CategoryRecipe'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_images', to='recipes.Recipe'),
        ),
    ]
