# Generated by Django 2.1 on 2018-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180810_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('Легко', 'Легко'), ('Легко', 'Средняя'), ('Легко', 'Тяжёлая')], default='Легко', max_length=8),
        ),
    ]
