# Generated by Django 2.1 on 2018-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredienttemplate_quatity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_serves',
            field=models.IntegerField(default=0),
        ),
    ]
