# Generated by Django 2.1 on 2018-08-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_recipe_serves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_serves',
        ),
    ]
